name = "radical"
main = "worker.js"
compatibility_date = "2024-03-31"

# D1 Database Binding
[[d1_databases]]
binding = "DB" # Use this name in your code
database_name = "radical-db"
database_id = "1f2a5273-bfcb-45c8-a759-5d675c05620c"

# R2 Bucket Binding
[[r2_buckets]]
binding = "MEMES_BUCKET"
bucket_name = "memes"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Main routes for API endpoints
[[routes]]
pattern = "theradicalparty.com/api/*"
zone_name = "theradicalparty.com"

# Media file routes
[[routes]]
pattern = "theradicalparty.com/memes/*"
zone_name = "theradicalparty.com"

[[routes]]
pattern = "theradicalparty.com/audio/*"
zone_name = "theradicalparty.com"

# Ensure static assets are properly routed
[[routes]]
pattern = "theradicalparty.com/styles.css"
zone_name = "theradicalparty.com"

# Pages integration
[pages]
build_command = "npm run build"
build_output_dir = "dist"



