name = "radical"
main = "worker.js"
compatibility_date = "2024-03-31"

# D1 Database Binding
[[d1_databases]]
binding = "DB" # Use this name in your code
database_name = "radical-db"
database_id = "1f2a5273-bfcb-45c8-a759-5d675c05620c"

# R2 Bucket Binding
[[r2_buckets]]
binding = "MEMES_BUCKET"
bucket_name = "memes"

# Static Assets Binding
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "assets"

# Environment variables
[vars]
ENVIRONMENT = "production"
# Add CORS_ALLOWED_ORIGINS if you want to restrict origins
# CORS_ALLOWED_ORIGINS = "theradicalparty.com,*.theradicalparty.com,localhost:*"

# Enhanced logging for troubleshooting
[observability.logs]
enabled = true
level = "debug"

# Routes configuration
[[routes]]
pattern = "theradicalparty.com/api/*"
zone_name = "theradicalparty.com"

[[routes]]
pattern = "theradicalparty.com/memes/*"
zone_name = "theradicalparty.com"

[[routes]]
pattern = "theradicalparty.com/audio/*"
zone_name = "theradicalparty.com"

[[routes]]
pattern = "theradicalparty.com/styles.css"
zone_name = "theradicalparty.com"

[[routes]]
pattern = "theradicalparty.com/"
zone_name = "theradicalparty.com"

# Explicitly add route for index.html
[[routes]]
pattern = "theradicalparty.com/index.html"
zone_name = "theradicalparty.com"

# Add route for login page
[[routes]]
pattern = "theradicalparty.com/login"
zone_name = "theradicalparty.com"

# Add route for manifest
[[routes]]
pattern = "theradicalparty.com/manifest.webmanifest"
zone_name = "theradicalparty.com"

# Configure CORS headers in wrangler.toml
[http_handlers]
[http_handlers.headers]
"Access-Control-Allow-Origin" = "*"
"Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
"Access-Control-Allow-Headers" = "Content-Type, Authorization, Accept, Cache-Control"
"Access-Control-Max-Age" = "86400"

# Pages integration if you're using Cloudflare Pages
[pages]
build_command = "npm run build"
build_output_dir = "dist"

# Triggers - useful if you need scheduled or cron jobs
[triggers]
crons = []